name: build
on:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Setup keystore
      run: echo "$keystore" | base64 -d - > ./keystore.jks
      env:
        keystore: '${{ secrets.keystore }}'
    - name: build
      run: ./gradlew build
      env:
        KEYSTORE: '../keystore.jks'
        KEYSTORE_PWD: '${{ secrets.keystorePwd }}'
        SIGNING_KEY: '${{ secrets.signingKey }}'
        SIGNING_KEY_PWD: '${{ secrets.signingKeyPwd }}'
    - name: upload apk
      uses: actions/upload-artifact@v2
      with:
        name: prebuilt APK
        path: app/build/outputs/apk/release/app-release.apk